apiVersion: v1
entries:
  cryptellation:
  - apiVersion: v1
    appVersion: 1.10.0
    created: "2024-06-13T18:16:06.753699+02:00"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.12.0
    - name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 0.19.13
    description: Cryptellation Platform
    digest: 8004b0b666b283c99ff7434d0acf88c73026368218be5499ec1ff292a0e137de
    name: cryptellation
    type: application
    urls:
    - https://lerenn.github.io/packages/helm/cryptellation/cryptellation-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v1
    appVersion: 0.8.2
    created: "2024-06-13T18:16:06.740018+02:00"
    dependencies:
    - name: cockroachdb
      repository: https://charts.cockroachdb.com/
      version: 10.0.8
    - name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 0.19.13
    description: Cryptellation Platform
    digest: 8d0fc3c37e1b7a122eaf1c7777a4b2d7e04ef19dae5fedd32579a3af16cb3af6
    name: cryptellation
    type: application
    urls:
    - https://lerenn.github.io/packages/helm/cryptellation/cryptellation-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v1
    appVersion: 0.8.2
    created: "2024-06-13T18:16:06.732834+02:00"
    dependencies:
    - name: cockroachdb
      repository: https://charts.cockroachdb.com/
      version: 10.0.8
    - name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 0.19.13
    description: Cryptellation Platform
    digest: 478315d1f3f1846f17224b6ba3dc045f7fc7451d04ea8c135877c60f85d7cf6a
    name: cryptellation
    type: application
    urls:
    - https://lerenn.github.io/packages/helm/cryptellation/cryptellation-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v1
    appVersion: 0.8.1
    created: "2024-06-13T18:16:06.722555+02:00"
    dependencies:
    - name: cockroachdb
      repository: https://charts.cockroachdb.com/
      version: 10.0.8
    - name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 0.19.13
    description: Cryptellation Platform
    digest: ed8f3ade7bc3fa9258c4c4218f52b9376da71818cb5d554e407bac3ce8175c55
    name: cryptellation
    type: application
    urls:
    - https://lerenn.github.io/packages/helm/cryptellation/cryptellation-1.0.0.tgz
    version: 1.0.0
generated: "2024-06-13T18:16:06.712935+02:00"
