apiVersion: v1
entries:
  cryptellation:
  - apiVersion: v1
    appVersion: 1.12.4
    created: "2024-08-20T11:48:23.481743831Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.12.0
    - name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 0.19.13
    description: Cryptellation Platform
    digest: a124379423c35e05324c0da8dc7651e4641bb0834e9f832233b73251582147a6
    name: cryptellation
    type: application
    urls:
    - https://lerenn.github.io/packages/helm/cryptellation/cryptellation-1.3.4.tgz
    version: 1.3.4
  - apiVersion: v1
    appVersion: 1.12.3
    created: "2024-08-20T11:48:23.475512666Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.12.0
    - name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 0.19.13
    description: Cryptellation Platform
    digest: e0d1fbbb6b3cba7b1450bfbd5214da0e98d38a1c2bdc3a7a3ff3309ce2194e5d
    name: cryptellation
    type: application
    urls:
    - https://lerenn.github.io/packages/helm/cryptellation/cryptellation-1.3.3.tgz
    version: 1.3.3
  - apiVersion: v1
    appVersion: 1.12.0
    created: "2024-08-20T11:48:23.469321872Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.12.0
    - name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 0.19.13
    description: Cryptellation Platform
    digest: f144a3277bd4b2ff62b9da55609c67058baedea47210a7969711853949b02e44
    name: cryptellation
    type: application
    urls:
    - https://lerenn.github.io/packages/helm/cryptellation/cryptellation-1.3.0.tgz
    version: 1.3.0
  - apiVersion: v1
    appVersion: 1.11.0
    created: "2024-08-20T11:48:23.463803208Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.12.0
    - name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 0.19.13
    description: Cryptellation Platform
    digest: d8bd8da3cd4a9e047b86f243ddafa878b29e022d70da65e538cab90064259aca
    name: cryptellation
    type: application
    urls:
    - https://lerenn.github.io/packages/helm/cryptellation/cryptellation-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v1
    appVersion: 1.10.0
    created: "2024-08-20T11:48:23.457566333Z"
    dependencies:
    - name: mongodb
      repository: https://charts.bitnami.com/bitnami
      version: 13.12.0
    - name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 0.19.13
    description: Cryptellation Platform
    digest: 8004b0b666b283c99ff7434d0acf88c73026368218be5499ec1ff292a0e137de
    name: cryptellation
    type: application
    urls:
    - https://lerenn.github.io/packages/helm/cryptellation/cryptellation-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v1
    appVersion: 0.8.2
    created: "2024-08-20T11:48:23.451196762Z"
    dependencies:
    - name: cockroachdb
      repository: https://charts.cockroachdb.com/
      version: 10.0.8
    - name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 0.19.13
    description: Cryptellation Platform
    digest: 8d0fc3c37e1b7a122eaf1c7777a4b2d7e04ef19dae5fedd32579a3af16cb3af6
    name: cryptellation
    type: application
    urls:
    - https://lerenn.github.io/packages/helm/cryptellation/cryptellation-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v1
    appVersion: 0.8.2
    created: "2024-08-20T11:48:23.448485796Z"
    dependencies:
    - name: cockroachdb
      repository: https://charts.cockroachdb.com/
      version: 10.0.8
    - name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 0.19.13
    description: Cryptellation Platform
    digest: 478315d1f3f1846f17224b6ba3dc045f7fc7451d04ea8c135877c60f85d7cf6a
    name: cryptellation
    type: application
    urls:
    - https://lerenn.github.io/packages/helm/cryptellation/cryptellation-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v1
    appVersion: 0.8.1
    created: "2024-08-20T11:48:23.443933603Z"
    dependencies:
    - name: cockroachdb
      repository: https://charts.cockroachdb.com/
      version: 10.0.8
    - name: nats
      repository: https://nats-io.github.io/k8s/helm/charts/
      version: 0.19.13
    description: Cryptellation Platform
    digest: ed8f3ade7bc3fa9258c4c4218f52b9376da71818cb5d554e407bac3ce8175c55
    name: cryptellation
    type: application
    urls:
    - https://lerenn.github.io/packages/helm/cryptellation/cryptellation-1.0.0.tgz
    version: 1.0.0
generated: "2024-08-20T11:48:23.440304959Z"
