apiVersion: v1
entries:
  otel-lgtm-dev:
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2023-09-28T18:07:20.655114038+04:00"
    dependencies:
    - name: opentelemetry-collector
      repository: https://open-telemetry.github.io/opentelemetry-helm-charts
      version: 0.68.1
    - name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 6.58.9
    - alias: loki
      name: loki-distributed
      repository: https://grafana.github.io/helm-charts
      version: 0.74.6
    - alias: mimir
      name: mimir-distributed
      repository: https://grafana.github.io/helm-charts
      version: 5.1.0
    - alias: tempo
      name: tempo-distributed
      repository: https://grafana.github.io/helm-charts
      version: 1.6.6
    description: OpenTelemetry + LGTM Stack for development
    digest: eb01ffe67b5b3a535fb7855c147db1e6fed36cb762f9f1c56b3d2b957d04fabf
    maintainers:
    - name: Louis FRADIN
    name: otel-lgtm-dev
    type: application
    urls:
    - https://github.com/lerenn/packages/helm/otel-lgtm-dev/otel-lgtm-dev-1.0.0.tgz
    version: 1.0.0
generated: "2023-09-28T18:07:20.615279734+04:00"
